### PR TITLE
Compute the closest face(s) to a finger tip sphere.

### PR DESCRIPTION
**Pull request by hongkai-dai**
This change is [Reviewable](https://reviewable.io/reviews/rcory/drake/37)

### CODE REVIEW

**Review by hongkai-dai — COMMENTED** [review]
+@rcory for feature review please, thanks!

> *[Reviewable](https://reviewable.io/reviews/rcory/drake/37#-:-M4bEp4u8C2BwdRpVaq8:bc785oo)* status: 0 of 4 files reviewed, all discussions resolved (waiting on @rcory)

**Review by rcory — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/rcory/drake/37)* status: all files reviewed, 1 unresolved discussion (waiting on @hongkai-dai)

___
*[examples/planar_gripper/planar_gripper_common.h, line 240 at r1](https://reviewable.io/reviews/rcory/drake/37#-M4kvYfaAo-B-8Fue7wq:-M4kvYfaAo-B-8Fue7wr:byaywrt) ([raw file](https://github.com/rcory/drake/blob/54d46e5e966fb2e5e234af2276b053fcb2dea52b/examples/planar_gripper/planar_gripper_common.h#L240)):*
> ```objc
>  * Otherwise we return the unique face on which the witness point lives.
>  */
> std::unordered_set<BrickFace> GetClosestFacesToFinger(
> ```

At some point I think a lot of the methods in `planar_gripper_common.h` should move into the `PlanarGripper` class in `planar_gripper.h/.cc`. I think this might be one that would make more sense to define there? 
___
*[examples/planar_gripper/planar_gripper_common.cc, line 540 at r1](https://reviewable.io/reviews/rcory/drake/37#-M4l02WbEXG4SzqlZILu:-M4l02Wc4ZcotNKHx81H:b-1jr2pj) ([raw file](https://github.com/rcory/drake/blob/54d46e5e966fb2e5e234af2276b053fcb2dea52b/examples/planar_gripper/planar_gripper_common.cc#L540)):*
> ```cpp
>           plant.GetBodyByName(to_string(finger) + "_tip_link").index()),
>       geometry::Role::kProximity, "planar_gripper::tip_sphere_collision");
> ```

Fyi, if we move `GetClosestFacesToFinger` to the `PlanarGripper` class in `planar_gripper.h/.cc`, then I think also adding member methods there that get these geometry id's is a good idea (I can see these being common enough to warrant having getter methods there. You also use it in your unit test.).

So, we'd have
`PlanarGripper::GetClosestFacesToFinger`
`PlanarGripper::GetFingertipSphereGeometryId`
`PlanarGripper::GetBrickGeometryId`

What do you think?

**Review by hongkai-dai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/rcory/drake/37)* status: 0 of 7 files reviewed, 1 unresolved discussion (waiting on @rcory)

___
*[examples/planar_gripper/planar_gripper_common.h, line 240 at r1](https://reviewable.io/reviews/rcory/drake/37#-M4kvYfaAo-B-8Fue7wq:-M4p62zZBQnLkOMbNHHN:b-896fix) ([raw file](https://github.com/rcory/drake/blob/54d46e5e966fb2e5e234af2276b053fcb2dea52b/examples/planar_gripper/planar_gripper_common.h#L240)):*
<details><summary><i>Previously, rcory (Rick Cory) wrote…</i></summary><blockquote>

At some point I think a lot of the methods in `planar_gripper_common.h` should move into the `PlanarGripper` class in `planar_gripper.h/.cc`. I think this might be one that would make more sense to define there? 
</blockquote></details>

Done.
___
*[examples/planar_gripper/planar_gripper_common.cc, line 540 at r1](https://reviewable.io/reviews/rcory/drake/37#-M4l02WbEXG4SzqlZILu:-M4p66Uo-mOoVfOhutN9:bvu5epd) ([raw file](https://github.com/rcory/drake/blob/54d46e5e966fb2e5e234af2276b053fcb2dea52b/examples/planar_gripper/planar_gripper_common.cc#L540)):*
<details><summary><i>Previously, rcory (Rick Cory) wrote…</i></summary><blockquote>

Fyi, if we move `GetClosestFacesToFinger` to the `PlanarGripper` class in `planar_gripper.h/.cc`, then I think also adding member methods there that get these geometry id's is a good idea (I can see these being common enough to warrant having getter methods there. You also use it in your unit test.).

So, we'd have
`PlanarGripper::GetClosestFacesToFinger`
`PlanarGripper::GetFingertipSphereGeometryId`
`PlanarGripper::GetBrickGeometryId`

What do you think?
</blockquote></details>

Done. I added the function in `PlanarGripper`.

**Review by rcory — CHANGES_REQUESTED** [review]
> Reviewed 7 of 7 files at r2.
> *[Reviewable](https://reviewable.io/reviews/rcory/drake/37)* status: all files reviewed, 6 unresolved discussions (waiting on @hongkai-dai and @rcory)

___
*[examples/planar_gripper/planar_gripper.cc, line 90 at r2](https://reviewable.io/reviews/rcory/drake/37#-M4pBD6JEbui1BWJLXW-:-M4pBD6JEbui1BWJLXW0:bl0e9ed) ([raw file](https://github.com/rcory/drake/blob/421591be837d6bcca415f5733e0a01064cec4c7e/examples/planar_gripper/planar_gripper.cc#L90)):*
> ```cpp
>   brick_geometry_id_ = inspector.GetGeometryIdByName(
>       plant->GetBodyFrameIdOrThrow(plant->GetBodyByName("brick_link").index()),
>       geometry::Role::kProximity, "brick::box_collision");
> ```

This chunk of code above should probably be in the  `PlanarGripper::SetupPlant()` method (not in the `AddFloor()` method)?
___
*[examples/planar_gripper/planar_gripper_common.h, line 7 at r2](https://reviewable.io/reviews/rcory/drake/37#-M4pAA0q09oadsw42uZs:-M4pAA0q09oadsw42uZt:b-sdzvih) ([raw file](https://github.com/rcory/drake/blob/421591be837d6bcca415f5733e0a01064cec4c7e/examples/planar_gripper/planar_gripper_common.h#L7)):*
> ```objc
> #include <string>
> #include <unordered_map>
> #include <unordered_set>
> ```

not needed anymore?
___
*[examples/planar_gripper/planar_gripper_common.h, line 225 at r2](https://reviewable.io/reviews/rcory/drake/37#-M4pBgQADyoLgyE1gELb:-M4pBeZX9KQyJs0yjR5d:b-njrb4n) ([raw file](https://github.com/rcory/drake/blob/412373620c62065f854f633298ee97bcd999bfa8/examples/planar_gripper/planar_gripper_common.h#L225)):*
> ```objc
>   MatrixX<double> Sx_;  // state selector matrix.
> };
> ```

fyi, is this deletion intentional?
___
*[examples/planar_gripper/planar_gripper_common.cc, line 525 at r2](https://reviewable.io/reviews/rcory/drake/37#-M4pBk-S5oI-V0X_w7vd:-M4pBk-S5oI-V0X_w7ve:b1zhukp) ([raw file](https://github.com/rcory/drake/blob/412373620c62065f854f633298ee97bcd999bfa8/examples/planar_gripper/planar_gripper_common.cc#L525)):*
> ```cpp
>   output_value = Sx_ * plant_state;  // User ordered state.
> }
> ```

Fyi, is this deletion intentional?
___
*[examples/planar_gripper/test/planar_gripper_common_test.cc, line 7 at r2](https://reviewable.io/reviews/rcory/drake/37#-M4pAPOo3VJwQlMeQ11f:-M4pAPOo3VJwQlMeQ11g:b-oat6ln) ([raw file](https://github.com/rcory/drake/blob/421591be837d6bcca415f5733e0a01064cec4c7e/examples/planar_gripper/test/planar_gripper_common_test.cc#L7)):*
> ```cpp
> #include "drake/common/find_resource.h"
> #include "drake/common/test_utilities/eigen_matrix_compare.h"
> #include "drake/multibody/inverse_kinematics/inverse_kinematics.h"
> ```

not needed here anymore?
___
*[examples/planar_gripper/test/planar_gripper_common_test.cc, line 10 at r2](https://reviewable.io/reviews/rcory/drake/37#-M4pARVt-i4kFR7OXDLr:-M4pARVt-i4kFR7OXDLs:b-oat6ln) ([raw file](https://github.com/rcory/drake/blob/421591be837d6bcca415f5733e0a01064cec4c7e/examples/planar_gripper/test/planar_gripper_common_test.cc#L10)):*
> ```cpp
> #include "drake/multibody/parsing/parser.h"
> #include "drake/multibody/plant/multibody_plant.h"
> #include "drake/solvers/solve.h"
> ```

not needed here anymore?
___
*[examples/planar_gripper/test/planar_gripper_common_test.cc, line 102 at r2](https://reviewable.io/reviews/rcory/drake/37#-M4pAOCS4DaHszA1-DbS:-M4pAOCS4DaHszA1-DbT:b-k10qr6) ([raw file](https://github.com/rcory/drake/blob/421591be837d6bcca415f5733e0a01064cec4c7e/examples/planar_gripper/test/planar_gripper_common_test.cc#L102)):*
> ```cpp
>       std::runtime_error);
> }
> ```

extra space?

**Review by hongkai-dai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/rcory/drake/37)* status: all files reviewed, 6 unresolved discussions (waiting on @hongkai-dai and @rcory)

___
*[examples/planar_gripper/planar_gripper.cc, line 90 at r2](https://reviewable.io/reviews/rcory/drake/37#-M4pBD6JEbui1BWJLXW-:-M4pFId-5DyjTKvjtPJd:b-yh16l6) ([raw file](https://github.com/rcory/drake/blob/421591be837d6bcca415f5733e0a01064cec4c7e/examples/planar_gripper/planar_gripper.cc#L90)):*
<details><summary><i>Previously, rcory (Rick Cory) wrote…</i></summary><blockquote>

This chunk of code above should probably be in the  `PlanarGripper::SetupPlant()` method (not in the `AddFloor()` method)?
</blockquote></details>

Done. Good call.
___
*[examples/planar_gripper/planar_gripper_common.h, line 225 at r2](https://reviewable.io/reviews/rcory/drake/37#-M4pBgQADyoLgyE1gELb:-M4pFV6e0aPVpGPwMMnL:b-h335yi) ([raw file](https://github.com/rcory/drake/blob/412373620c62065f854f633298ee97bcd999bfa8/examples/planar_gripper/planar_gripper_common.h#L225)):*
<details><summary><i>Previously, rcory (Rick Cory) wrote…</i></summary><blockquote>

fyi, is this deletion intentional?
</blockquote></details>

No, it is not.
___
*[examples/planar_gripper/planar_gripper_common.cc, line 525 at r2](https://reviewable.io/reviews/rcory/drake/37#-M4pBk-S5oI-V0X_w7vd:-M4pFWvGEt_ZKJFvGlbY:b-h335yi) ([raw file](https://github.com/rcory/drake/blob/412373620c62065f854f633298ee97bcd999bfa8/examples/planar_gripper/planar_gripper_common.cc#L525)):*
<details><summary><i>Previously, rcory (Rick Cory) wrote…</i></summary><blockquote>

Fyi, is this deletion intentional?
</blockquote></details>

No, it is not.
___
*[examples/planar_gripper/test/planar_gripper_common_test.cc, line 7 at r2](https://reviewable.io/reviews/rcory/drake/37#-M4pAPOo3VJwQlMeQ11f:-M4pFoDx5Ligxgiw5313:b-896fix) ([raw file](https://github.com/rcory/drake/blob/421591be837d6bcca415f5733e0a01064cec4c7e/examples/planar_gripper/test/planar_gripper_common_test.cc#L7)):*
<details><summary><i>Previously, rcory (Rick Cory) wrote…</i></summary><blockquote>

not needed here anymore?
</blockquote></details>

Done.
___
*[examples/planar_gripper/test/planar_gripper_common_test.cc, line 10 at r2](https://reviewable.io/reviews/rcory/drake/37#-M4pARVt-i4kFR7OXDLr:-M4pFpxn27TzwpITaexa:b-896fix) ([raw file](https://github.com/rcory/drake/blob/421591be837d6bcca415f5733e0a01064cec4c7e/examples/planar_gripper/test/planar_gripper_common_test.cc#L10)):*
<details><summary><i>Previously, rcory (Rick Cory) wrote…</i></summary><blockquote>

not needed here anymore?
</blockquote></details>

Done.
___
*[examples/planar_gripper/test/planar_gripper_common_test.cc, line 102 at r2](https://reviewable.io/reviews/rcory/drake/37#-M4pAOCS4DaHszA1-DbS:-M4pG7ZR2Vxd1zUfEJ_l:b-896fix) ([raw file](https://github.com/rcory/drake/blob/421591be837d6bcca415f5733e0a01064cec4c7e/examples/planar_gripper/test/planar_gripper_common_test.cc#L102)):*
<details><summary><i>Previously, rcory (Rick Cory) wrote…</i></summary><blockquote>

extra space?
</blockquote></details>

Done.

**Review by rcory — APPROVED** [review]
:lgtm: 

> Reviewed 4 of 4 files at r3.
> *[Reviewable](https://reviewable.io/reviews/rcory/drake/37#-:-M4pIzRj52fUxaZyJvWS:bg7igkv)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by rcory — APPROVED** [review]
Looks like there's a CI failure.

> *[Reviewable](https://reviewable.io/reviews/rcory/drake/37#-:-M4pJ8RG-1mr6NUOoKXq:b-78wzs9)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by rcory — APPROVED** [review]
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/rcory/drake/37)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
