### PR TITLE
Fix most of CI failure.

### PR DESCRIPTION
**Pull request by hongkai-dai**
CI still fails on run_playback_gripper_keyframes_test. @rcory could you fix that test?

---
This change is [Reviewable](https://reviewable.io/reviews/rcory/drake/11)

### CODE REVIEW

**Review by hongkai-dai — COMMENTED** [review]
+@rcory for review please, thanks!

> *[Reviewable](https://reviewable.io/reviews/rcory/drake/11#-:-M29c2V75iJWIzo0Cwj3:b-hpcvc2)* status: 0 of 26 files reviewed, all discussions resolved (waiting on @rcory)

**Review by rcory — APPROVED** [review]
:lgtm:  (with one minor typo fix)

> Reviewed 26 of 26 files at r1.
> *[Reviewable](https://reviewable.io/reviews/rcory/drake/11#-:-M2Fu8NS7nWQr1-vUWhQ:b-mpcc8o)* status: all files reviewed, 1 unresolved discussion (waiting on @hongkai-dai)

___
*[examples/planar_gripper/planar_gripper.h, line 105 at r1](https://reviewable.io/reviews/rcory/drake/11#-M2FmKdW0GxmjG9D1KVx:-M2FmKdW0GxmjG9D1KVy:bayqnkx) ([raw file](https://github.com/rcory/drake/blob/3a26b6314c74a7d5abbbe4c451e03258be9124af/examples/planar_gripper/planar_gripper.h#L105)):*
> ```objc
> 
>   /// Convenience method for getting all of the joint velocities of the Kuka
>   // IIWA.  This does not include the gripper.
> ```

My copy/paste error. "Kuka IIWA" should be "Gripper"

**Review by hongkai-dai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/rcory/drake/11)* status: all files reviewed, 1 unresolved discussion (waiting on @rcory)

___
*[examples/planar_gripper/planar_gripper.h, line 105 at r1](https://reviewable.io/reviews/rcory/drake/11#-M2FmKdW0GxmjG9D1KVx:-M2Fwlk23WkmecqWJQdb:b-896fix) ([raw file](https://github.com/rcory/drake/blob/3a26b6314c74a7d5abbbe4c451e03258be9124af/examples/planar_gripper/planar_gripper.h#L105)):*
<details><summary><i>Previously, rcory (Rick Cory) wrote…</i></summary><blockquote>

My copy/paste error. "Kuka IIWA" should be "Gripper"
</blockquote></details>

Done.

**Review by rcory — APPROVED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/rcory/drake/11)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
