### PR TITLE
Planar gripper udp fake sim

### PR DESCRIPTION
**Pull request by hongkai-dai**
This change is [Reviewable](https://reviewable.io/reviews/rcory/drake/4)

### CODE REVIEW

**Review by rcory — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/rcory/drake/4)* status: all files reviewed, 4 unresolved discussions (waiting on @hongkai-dai)

___
*[examples/planar_gripper/planar_gripper_udp.h, line 373 at r1](https://reviewable.io/reviews/rcory/drake/4#-M1QsA7r8nHdOBz7nWFn:-M1QsA7s1kfd24LDuQHN:b9gusox) ([raw file](https://github.com/rcory/drake/blob/38cb0592270ac17bece014240f94ddb349c20a7d/examples/planar_gripper/planar_gripper_udp.h#L373)):*
> ```objc
> /**
>  * This is a fake simulation publisher system. It is wired to the QP controller
>  * output, and publishes the spatial forces to UDP.
> ```

nit I'd probably simplify the description to:

"This system is wired to the QP controller outputs, which are published via UDP."
___
*[examples/planar_gripper/planar_gripper_udp.h, line 422 at r1](https://reviewable.io/reviews/rcory/drake/4#-M1ChMoz2btZp4M5FUnC:-M1ChMp-9IHB6pbg6eOe:bn99mkp) ([raw file](https://github.com/rcory/drake/blob/38cb0592270ac17bece014240f94ddb349c20a7d/examples/planar_gripper/planar_gripper_udp.h#L422)):*
> ```objc
> 
> // A system that subscribes to the simulation and publishes to the simulation.
> class PlanarGripperSimulationUdp : public systems::Diagram<double> {
> ```

nit capitalize `Udp` -> `UDP` to match the QP controller version above. (I just realized I made the same typo mistake on the LCM version).
___
*[examples/planar_gripper/planar_gripper_udp.cc, line 568 at r1](https://reviewable.io/reviews/rcory/drake/4#-M1QtxKv-3H1ZYxs0WaJ:-M1QtxKv-3H1ZYxs0WaK:boo8b7j) ([raw file](https://github.com/rcory/drake/blob/38cb0592270ac17bece014240f94ddb349c20a7d/examples/planar_gripper/planar_gripper_udp.cc#L568)):*
> ```cpp
> 
>   plant_state_index_ = this->DeclareDiscreteState(num_plant_states_);
>   finger_face_state_index_ = this->DeclareAbstractState(
> ```

Shouldn't this be called `finger_face_assignments_index`? (to make it consistent with the other index names here)
___
*[examples/planar_gripper/planar_gripper_udp.cc, line 583 at r1](https://reviewable.io/reviews/rcory/drake/4#-M1QuqgBBpmhBW21ViC0:-M1QuqgBBpmhBW21ViC1:b-sni88d) ([raw file](https://github.com/rcory/drake/blob/38cb0592270ac17bece014240f94ddb349c20a7d/examples/planar_gripper/planar_gripper_udp.cc#L583)):*
> ```cpp
>               &QPtoSimUdpReceiverSystem::OutputEstimatedPlantState)
>           .get_index();
>   finger_face_output_port_ =
> ```

`finger_face_assignments_output_port`?

I think my confusion is that sometimes you use the whole name `finger_face_assignments` and other times you use the shortened name `finger_face`, when defining different variables. It's probably better to pick one and stay consistent.

**Review by rcory — COMMENTED** [review]
Fyi, I realized that the phrases "fake sim" and "fake qp controller" can be a little confusing. Perhaps better to call them "UDP sim wrapper" and "UDP qp controller wrapper".

> *[Reviewable](https://reviewable.io/reviews/rcory/drake/4#-:-M1QwprgDzxNJuXySTJy:btuk6g8)* status: all files reviewed, 4 unresolved discussions (waiting on @hongkai-dai)

**Review by hongkai-dai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/rcory/drake/4)* status: 1 of 3 files reviewed, 2 unresolved discussions (waiting on @rcory)

___
*[examples/planar_gripper/planar_gripper_udp.h, line 373 at r1](https://reviewable.io/reviews/rcory/drake/4#-M1QsA7r8nHdOBz7nWFn:-M1R567m-ap-hPomDdRp:b-896fix) ([raw file](https://github.com/rcory/drake/blob/38cb0592270ac17bece014240f94ddb349c20a7d/examples/planar_gripper/planar_gripper_udp.h#L373)):*
<details><summary><i>Previously, rcory (Rick Cory) wrote…</i></summary><blockquote>

nit I'd probably simplify the description to:

"This system is wired to the QP controller outputs, which are published via UDP."
</blockquote></details>

Done.
___
*[examples/planar_gripper/planar_gripper_udp.cc, line 568 at r1](https://reviewable.io/reviews/rcory/drake/4#-M1QtxKv-3H1ZYxs0WaJ:-M1R5ezj8Q0Bif-tzvYi:b-896fix) ([raw file](https://github.com/rcory/drake/blob/38cb0592270ac17bece014240f94ddb349c20a7d/examples/planar_gripper/planar_gripper_udp.cc#L568)):*
<details><summary><i>Previously, rcory (Rick Cory) wrote…</i></summary><blockquote>

Shouldn't this be called `finger_face_assignments_index`? (to make it consistent with the other index names here)
</blockquote></details>

Done.
___
*[examples/planar_gripper/planar_gripper_udp.cc, line 583 at r1](https://reviewable.io/reviews/rcory/drake/4#-M1QuqgBBpmhBW21ViC0:-M1R5t-9-Ce2eu45ZKJN:b-896fix) ([raw file](https://github.com/rcory/drake/blob/38cb0592270ac17bece014240f94ddb349c20a7d/examples/planar_gripper/planar_gripper_udp.cc#L583)):*
<details><summary><i>Previously, rcory (Rick Cory) wrote…</i></summary><blockquote>

`finger_face_assignments_output_port`?

I think my confusion is that sometimes you use the whole name `finger_face_assignments` and other times you use the shortened name `finger_face`, when defining different variables. It's probably better to pick one and stay consistent.
</blockquote></details>

Done.

**Review by rcory — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/rcory/drake/4#-:-M1RFLYJEuolhKKCFBZG:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
