### PR TITLE
Return the witness point on the brick together with the closest faces.

### PR DESCRIPTION
**Pull request by hongkai-dai**
This change is [Reviewable](https://reviewable.io/reviews/rcory/drake/40)

### CODE REVIEW

**Review by hongkai-dai — COMMENTED** [review]
+@rcory for feature review please, thanks!

> *[Reviewable](https://reviewable.io/reviews/rcory/drake/40#-:-M4u0OQd6jWBDdtXhHTT:bc785oo)* status: 0 of 4 files reviewed, all discussions resolved (waiting on @rcory)

**Review by rcory — APPROVED** [review]
:lgtm: 

> Reviewed 4 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/rcory/drake/40#-:-M4uIh_2Ak-srbglf8un:bg7igkv)* status: all files reviewed, 1 unresolved discussion (waiting on @hongkai-dai)

___
*[examples/planar_gripper/test/planar_gripper_test.cc, line 81 at r1](https://reviewable.io/reviews/rcory/drake/40#-M4uIOD65ZiG4_T-nO3u:-M4uIOD65ZiG4_T-nO3v:b7f42re) ([raw file](https://github.com/rcory/drake/blob/856ecb6944851096cb945a16565310aa193654e2/examples/planar_gripper/test/planar_gripper_test.cc#L81)):*
> ```cpp
>   EXPECT_EQ(closest_faces, std::unordered_set<BrickFace>({BrickFace::kPosZ}));
>   Eigen::Vector3d
>       p_BS;  // position of finger tip sphere center S in the brick frame B.
> ```

nit, this formatting is odd. Perhaps put the comment on top of the line.

**Review by hongkai-dai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/rcory/drake/40)* status: 3 of 4 files reviewed, all discussions resolved (waiting on @rcory)

___
*[examples/planar_gripper/test/planar_gripper_test.cc, line 81 at r1](https://reviewable.io/reviews/rcory/drake/40#-M4uIOD65ZiG4_T-nO3u:-M4uYX6r9eeUArlWWu9s:b-896fix) ([raw file](https://github.com/rcory/drake/blob/856ecb6944851096cb945a16565310aa193654e2/examples/planar_gripper/test/planar_gripper_test.cc#L81)):*
<details><summary><i>Previously, rcory (Rick Cory) wrote…</i></summary><blockquote>

nit, this formatting is odd. Perhaps put the comment on top of the line.
</blockquote></details>

Done.

**Review by rcory — APPROVED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/rcory/drake/40)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
