### PR TITLE
Add a FingerFaceAssigner leaf system.

### PR DESCRIPTION
**Pull request by hongkai-dai**
This system outputs the closest face and the witness point for each finger.

---
This change is [Reviewable](https://reviewable.io/reviews/rcory/drake/41)

### CODE REVIEW

**Review by hongkai-dai — COMMENTED** [review]
+@rcory for review please, thanks!

> *[Reviewable](https://reviewable.io/reviews/rcory/drake/41#-:-M4zz5x8Ba_y6_KC2EJi:b-hpcvc2)* status: 0 of 3 files reviewed, all discussions resolved (waiting on @rcory)

**Review by rcory — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/rcory/drake/41)* status: all files reviewed, 4 unresolved discussions (waiting on @hongkai-dai)

___
*[examples/planar_gripper/planar_gripper.h, line 323 at r1](https://reviewable.io/reviews/rcory/drake/41#-M52_McQ3OhrfrS6O6RS:-M52_McQ3OhrfrS6O6RT:bqsphqh) ([raw file](https://github.com/rcory/drake/blob/624382bc8d85b1ee2956ac05d3376bdba8228398/examples/planar_gripper/planar_gripper.h#L323)):*
> ```objc
> /**
>  * Compute the closest face(s) to a center finger given the posture.
>  * When the witness point on the brick is at the vertex of the brick, then
> ```

nit These two sentences are repeated for the @return parameter below. Probably not needed?
___
*[examples/planar_gripper/planar_gripper.cc, line 248 at r1](https://reviewable.io/reviews/rcory/drake/41#-M52cCzfADrgVd8cRB84:-M52cCzfADrgVd8cRB85:bjhr53v) ([raw file](https://github.com/rcory/drake/blob/624382bc8d85b1ee2956ac05d3376bdba8228398/examples/planar_gripper/planar_gripper.cc#L248)):*
> ```cpp
>       plant.GetBodyFrameIdOrThrow(plant.GetBodyByName("brick_link").index()),
>       geometry::Role::kProximity, "brick::box_collision");
> }
> ```

These methods also exist in `finger_brick.cc`. Perhaps we want to remove duplicate code?
___
*[examples/planar_gripper/planar_gripper.cc, line 602 at r1](https://reviewable.io/reviews/rcory/drake/41#-M52qZ3g9XTkJFhFriHe:-M52qZ3g9XTkJFhFriHf:b-az73g9) ([raw file](https://github.com/rcory/drake/blob/624382bc8d85b1ee2956ac05d3376bdba8228398/examples/planar_gripper/planar_gripper.cc#L602)):*
> ```cpp
>   const auto& inspector = scene_graph_.model_inspector();
>   for (const auto finger :
>        {Finger::kFinger1, Finger::kFinger2, Finger::kFinger3}) {
> ```

nit Consider passing in the fingers to the constructor. At some point (e.g., when we have Allegro) kNumFingers==4, and this will be wrong. Not a big deal now, though.
___
*[examples/planar_gripper/planar_gripper.cc, line 627 at r1](https://reviewable.io/reviews/rcory/drake/41#-M52mlQx3ppEXLO4l-cE:-M52mlQx3ppEXLO4l-cF:b-i73jfg) ([raw file](https://github.com/rcory/drake/blob/624382bc8d85b1ee2956ac05d3376bdba8228398/examples/planar_gripper/planar_gripper.cc#L627)):*
> ```cpp
>   for (const auto& finger_id_pair : finger_sphere_geometry_ids_) {
>     const std::pair<std::unordered_set<BrickFace>, Eigen::Vector3d>
>         finger_faces = GetClosestFacesToFingerImpl(
> ```

Sorry, but looking at this now, I'm again wondering...couldn't we just call the public method `GetClosestFacesToFinger(plant_, scene_graph_, context, finger)` here instead of needing the `Impl` version?

Also, what isn't immediately clear to me in this call, is the `GetClosestFacesToFingerImpl` takes in a `plant_context`, but this is passing in the `context` parameter of this leaf system which is a `FingerFaceAssigner` context? My reasoning must be wrong...since your unit test seems to work.

**Review by rcory — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/rcory/drake/41)* status: all files reviewed, 5 unresolved discussions (waiting on @hongkai-dai)

___
*[examples/planar_gripper/planar_gripper.cc, line 551 at r1](https://reviewable.io/reviews/rcory/drake/41#-M5313mc6mompFARbjo7:-M5313mc6mompFARbjo8:b-wdrutw) ([raw file](https://github.com/rcory/drake/blob/624382bc8d85b1ee2956ac05d3376bdba8228398/examples/planar_gripper/planar_gripper.cc#L551)):*
> ```cpp
>                             geometry::GeometryId brick_geometry_id,
>                             const systems::InputPort<double>& query_port,
>                             const systems::Context<double>& plant_context) {
> ```

`plant_context` should be renamed `system_context`. In my head `plant` usually refers to the MBP, but in this case the context can come from either a MBP or a `FingerFaceAssigner` system.
___
*[examples/planar_gripper/planar_gripper.cc, line 627 at r1](https://reviewable.io/reviews/rcory/drake/41#-M52mlQx3ppEXLO4l-cE:-M530rRs7LbWcKigAOab:b4g0ywj) ([raw file](https://github.com/rcory/drake/blob/624382bc8d85b1ee2956ac05d3376bdba8228398/examples/planar_gripper/planar_gripper.cc#L627)):*
<details><summary><i>Previously, rcory (Rick Cory) wrote…</i></summary><blockquote>

Sorry, but looking at this now, I'm again wondering...couldn't we just call the public method `GetClosestFacesToFinger(plant_, scene_graph_, context, finger)` here instead of needing the `Impl` version?

Also, what isn't immediately clear to me in this call, is the `GetClosestFacesToFingerImpl` takes in a `plant_context`, but this is passing in the `context` parameter of this leaf system which is a `FingerFaceAssigner` context? My reasoning must be wrong...since your unit test seems to work.
</blockquote></details>

Update: I just realized my confusion stems from the naming of the context parameter in `GetClosestFacesToFingerImpl` (see comment there).

**Review by hongkai-dai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/rcory/drake/41)* status: all files reviewed, 4 unresolved discussions (waiting on @rcory)

___
*[examples/planar_gripper/planar_gripper.h, line 323 at r1](https://reviewable.io/reviews/rcory/drake/41#-M52_McQ3OhrfrS6O6RS:-M5DNnkX1jPUfALbC7AF:b-896fix) ([raw file](https://github.com/rcory/drake/blob/624382bc8d85b1ee2956ac05d3376bdba8228398/examples/planar_gripper/planar_gripper.h#L323)):*
<details><summary><i>Previously, rcory (Rick Cory) wrote…</i></summary><blockquote>

nit These two sentences are repeated for the @return parameter below. Probably not needed?
</blockquote></details>

Done.
___
*[examples/planar_gripper/planar_gripper.cc, line 248 at r1](https://reviewable.io/reviews/rcory/drake/41#-M52cCzfADrgVd8cRB84:-M5DUwsc2vljDwabK96E:bn6csey) ([raw file](https://github.com/rcory/drake/blob/624382bc8d85b1ee2956ac05d3376bdba8228398/examples/planar_gripper/planar_gripper.cc#L248)):*
<details><summary><i>Previously, rcory (Rick Cory) wrote…</i></summary><blockquote>

These methods also exist in `finger_brick.cc`. Perhaps we want to remove duplicate code?
</blockquote></details>

Done. I also restructured the code to create `planar_gripper_utils.h` file. Now `planar_gripper.h` only contains `PlanarGripper` class.
___
*[examples/planar_gripper/planar_gripper.cc, line 551 at r1](https://reviewable.io/reviews/rcory/drake/41#-M5313mc6mompFARbjo7:-M5DV_nMBIm3owo-YUKj:b-48vilg) ([raw file](https://github.com/rcory/drake/blob/624382bc8d85b1ee2956ac05d3376bdba8228398/examples/planar_gripper/planar_gripper.cc#L551)):*
<details><summary><i>Previously, rcory (Rick Cory) wrote…</i></summary><blockquote>

`plant_context` should be renamed `system_context`. In my head `plant` usually refers to the MBP, but in this case the context can come from either a MBP or a `FingerFaceAssigner` system.
</blockquote></details>

Good call, done.
___
*[examples/planar_gripper/planar_gripper.cc, line 602 at r1](https://reviewable.io/reviews/rcory/drake/41#-M52qZ3g9XTkJFhFriHe:-M5DW7e18cYkqvMmVTT1:b-ru9dba) ([raw file](https://github.com/rcory/drake/blob/624382bc8d85b1ee2956ac05d3376bdba8228398/examples/planar_gripper/planar_gripper.cc#L602)):*
<details><summary><i>Previously, rcory (Rick Cory) wrote…</i></summary><blockquote>

nit Consider passing in the fingers to the constructor. At some point (e.g., when we have Allegro) kNumFingers==4, and this will be wrong. Not a big deal now, though.
</blockquote></details>

Right below we have `DRAKE_DEMAND(static_cast<int>(finger_sphere_geometry_ids_.size()) == kNumFingers)`, which intends to catch the failure when `kNumFingers` changes.
___
*[examples/planar_gripper/planar_gripper.cc, line 627 at r1](https://reviewable.io/reviews/rcory/drake/41#-M52mlQx3ppEXLO4l-cE:-M5DWYcH7aXn8lFp5GaK:b-2eu4sf) ([raw file](https://github.com/rcory/drake/blob/624382bc8d85b1ee2956ac05d3376bdba8228398/examples/planar_gripper/planar_gripper.cc#L627)):*
<details><summary><i>Previously, rcory (Rick Cory) wrote…</i></summary><blockquote>

Update: I just realized my confusion stems from the naming of the context parameter in `GetClosestFacesToFingerImpl` (see comment there).
</blockquote></details>

I think this is resolved? In `GetClosestFacesToFingerImpl` the name of the variable is `system_context`. I also added more documentation to explain what this context should be. The requirement for this `system_context` is that we should be able to evaluate `GeometryQuery` using this context.

For `GetClosestFacesToFinger` function, since we evaluate the context at `plant.get_geometry_query_input_port()`, so it should be `plant_context`. I also added more documentation to `GetClosestFacesToFinger` function to explain how to obtain `plant_context`.

**Review by rcory — APPROVED** [review]
:lgtm: 

> Reviewed 10 of 10 files at r2.
> *[Reviewable](https://reviewable.io/reviews/rcory/drake/41#-:-M5NS3y9CAktc-J5SRzQ:bg7igkv)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[examples/planar_gripper/planar_gripper_utils.h, line 27 at r2](https://reviewable.io/reviews/rcory/drake/41#-M5N93NO5rocmOlTH18P:-M5N93NP4bEw5FrT9zzx:b-z06qay) ([raw file](https://github.com/rcory/drake/blob/b3f1b10270098659fccaa70d31e664e35c9c164a/examples/planar_gripper/planar_gripper_utils.h#L27)):*
> ```objc
> 
> /**
>  * Compute the closest face(s) to a center finger given the posture.
> ```

fyi "center finger" --> "fingertip sphere center"?
___
*[examples/planar_gripper/planar_gripper_utils.h, line 41 at r2](https://reviewable.io/reviews/rcory/drake/41#-M5N9qSr0vqGTDjzOUsz:-M5N9qSr0vqGTDjzOUt-:b6b7wjg) ([raw file](https://github.com/rcory/drake/blob/b3f1b10270098659fccaa70d31e664e35c9c164a/examples/planar_gripper/planar_gripper_utils.h#L41)):*
> ```objc
>  * auto diagram = builder.Build();
>  * auto diagram_context = builder.CreateDefaultContext();
>  * auto plant_context = diagram.GetSubsystemContect(*plant, diagram_context);
> ```

fyi `*plant` should be just `plant`?
___
*[examples/planar_gripper/planar_gripper_utils.h, line 43 at r2](https://reviewable.io/reviews/rcory/drake/41#-M5NA-uM8_UECkYy5kH2:-M5NA-uM8_UECkYy5kH3:bau9esl) ([raw file](https://github.com/rcory/drake/blob/b3f1b10270098659fccaa70d31e664e35c9c164a/examples/planar_gripper/planar_gripper_utils.h#L43)):*
> ```objc
>  * auto plant_context = diagram.GetSubsystemContect(*plant, diagram_context);
>  * @endcode
>  * @param finger The finger to which the closest faces are queried.
> ```

fyi "finger to which" should be "Finger to which" (capitalized Finger)

**Pull request merged**
