### PR TITLE
Updates FingerFaceAssigner

### PR DESCRIPTION
**Pull request by rcory**
* Updates FingerFaceAssigner and integrates it into existing demos/tests.

* Removes ContactPointInBrickFrame and ContactPointsToFingerFaceAssignment
leaf systems (no longer needed).

* Adds a ForceController integration test, which checks that actual force
matches desired force, for a simple steady-state force-regulation task.

---
This change is [Reviewable](https://reviewable.io/reviews/rcory/drake/47)

### CODE REVIEW

**Review by rcory — COMMENTED** [review]
+@hongkai-dai for review, please.

> *[Reviewable](https://reviewable.io/reviews/rcory/drake/47#-:-M65ozPhACM2hBdYNB-x:b-caag4n)* status: 0 of 19 files reviewed, all discussions resolved (waiting on @hongkai-dai)

**Review by hongkai-dai — CHANGES_REQUESTED** [review]
> Reviewed 16 of 19 files at r1.
> *[Reviewable](https://reviewable.io/reviews/rcory/drake/47)* status: 16 of 19 files reviewed, 8 unresolved discussions (waiting on @hongkai-dai and @rcory)

___
*[examples/planar_gripper/planar_gripper_utils.h, line 22 at r1](https://reviewable.io/reviews/rcory/drake/47#-M66LuCpCK_YHPcyC6fz:-M66LuCpCK_YHPcyC6g-:b8j5mpd) ([raw file](https://github.com/rcory/drake/blob/bedc7b74c98f3ebc03c35c0a460cc733ffc9080b/examples/planar_gripper/planar_gripper_utils.h#L22)):*
> ```objc
>         p_BCb(point),
>         is_in_contact(contact) {}
>   BrickFace brick_face;   //  the brick face this finger is assigned to.
> ```

Do you think that `brick_face, p_BCb, is_in_contact` would change in the future? If not, then maybe make them to be const data members?
___
*[examples/planar_gripper/planar_gripper_utils.h, line 96 at r1](https://reviewable.io/reviews/rcory/drake/47#-M66Mukb99EsbdatBG6Z:-M66Mukb99EsbdatBG6_:bd0l9ru) ([raw file](https://github.com/rcory/drake/blob/bedc7b74c98f3ebc03c35c0a460cc733ffc9080b/examples/planar_gripper/planar_gripper_utils.h#L96)):*
> ```objc
>   FingerFaceAssigner(const multibody::MultibodyPlant<double>& plant,
>                      const geometry::SceneGraph<double>& scene_graph,
>                      const std::vector<Finger> fingers = {
> ```

Could you document why we need to pass `fingers`? Also the input type should be `const std::vector<Finger>&` (const reference).
___
*[examples/planar_gripper/planar_gripper_utils.h, line 150 at r1](https://reviewable.io/reviews/rcory/drake/47#-M66aGHb20bEas75v9KQ:-M66aGHb20bEas75v9KR:b-5hrhk9) ([raw file](https://github.com/rcory/drake/blob/bedc7b74c98f3ebc03c35c0a460cc733ffc9080b/examples/planar_gripper/planar_gripper_utils.h#L150)):*
> ```objc
> /// information is found. If it isn't found, then
> /// index = contact_results.num_point_pair_contacts()
> int GetContactPairIndex(
> ```

Maybe instead of returning `int`, and relies on `contact_results.num_point_pair_contacts()` to indicate not found, we could use `std::optional<int>`. If the std::optional<int>()::has_value() is false, then it means the index is not found.
___
*[examples/planar_gripper/planar_gripper_utils.cc, line 150 at r1](https://reviewable.io/reviews/rcory/drake/47#-M6AmNrc5VEj6ey8mKEw:-M6AmNrc5VEj6ey8mKEx:b-obglxk) ([raw file](https://github.com/rcory/drake/blob/bedc7b74c98f3ebc03c35c0a460cc733ffc9080b/examples/planar_gripper/planar_gripper_utils.cc#L150)):*
> ```cpp
> 
>     // If the geometries are in contact, return the actual contact point.
>     // Otherwise, return the witness point. Both are expressed in brick frame.
> ```

Just curious, what is the difference between the actual contact point and the witness point when the geometries are in contact? The witness point would be the point with the deepest penetration, so the witness point may not be on the brick surface when the finger penetrates into the brick slightly. Would the contact point computed from `contact_results` be exactly on the brick surface? How does `contact_result` compute the contact point in the first place?
___
*[examples/planar_gripper/planar_gripper_utils.cc, line 234 at r1](https://reviewable.io/reviews/rcory/drake/47#-M6Apbnd4nHOAbxu_F-4:-M6Apbne4LH6GcL15Vho:b-8q1f8q) ([raw file](https://github.com/rcory/drake/blob/bedc7b74c98f3ebc03c35c0a460cc733ffc9080b/examples/planar_gripper/planar_gripper_utils.cc#L234)):*
> ```cpp
> 
> std::unordered_map<Finger, BrickFaceInfo> BrickSpatialForceAssignments(
>     std::unordered_set<Finger> fingers_to_control) {
> ```

input type should be `const std::unordered_set<Finger>&`?
___
*[examples/planar_gripper/planar_gripper_utils.cc, line 237 at r1](https://reviewable.io/reviews/rcory/drake/47#-M6App-Q1qq-ANRDOug5:-M6App-Q1qq-ANRDOug6:b-gxd8wt) ([raw file](https://github.com/rcory/drake/blob/bedc7b74c98f3ebc03c35c0a460cc733ffc9080b/examples/planar_gripper/planar_gripper_utils.cc#L237)):*
> ```cpp
>   std::unordered_map<Finger, BrickFaceInfo> brick_spatial_force_assignments;
>   // Iterate over virtual fingers (i.e., spatial forces) for brick only sim.
>   constexpr double kBoxDimension = 0.1;
> ```

Just curious, why using `constexpr` instead of `const`? I don't think we need `kBoxDimension` to be a compile-time const?
___
*[examples/planar_gripper/planar_gripper_utils.cc, line 238 at r1](https://reviewable.io/reviews/rcory/drake/47#-M6Apuiq-TcTtGKp-Zu_:-M6Apuiq-TcTtGKp-Zua:b-9d7p7a) ([raw file](https://github.com/rcory/drake/blob/bedc7b74c98f3ebc03c35c0a460cc733ffc9080b/examples/planar_gripper/planar_gripper_utils.cc#L238)):*
> ```cpp
>   // Iterate over virtual fingers (i.e., spatial forces) for brick only sim.
>   constexpr double kBoxDimension = 0.1;
>   for (auto& finger : fingers_to_control) {
> ```

const auto&?
___
*[examples/planar_gripper/test/force_control_test.cc, line 57 at r1](https://reviewable.io/reviews/rcory/drake/47#-M6AqU2HBjkfrJc9WVPj:-M6AqU2I-IyJ4ZjQojsO:b2imrb) ([raw file](https://github.com/rcory/drake/blob/bedc7b74c98f3ebc03c35c0a460cc733ffc9080b/examples/planar_gripper/test/force_control_test.cc#L57)):*
> ```cpp
>   plant->Finalize();
> 
>   plant->set_penetration_allowance(0.2);
> ```

Curious why we need such a large penetration allowance.

**Review by rcory — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/rcory/drake/47)* status: 13 of 19 files reviewed, 8 unresolved discussions (waiting on @hongkai-dai)

___
*[examples/planar_gripper/planar_gripper_utils.h, line 22 at r1](https://reviewable.io/reviews/rcory/drake/47#-M66LuCpCK_YHPcyC6fz:-M6BVZthAwLG6m0-Kfhr:b-z5liv9) ([raw file](https://github.com/rcory/drake/blob/bedc7b74c98f3ebc03c35c0a460cc733ffc9080b/examples/planar_gripper/planar_gripper_utils.h#L22)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Do you think that `brick_face, p_BCb, is_in_contact` would change in the future? If not, then maybe make them to be const data members?
</blockquote></details>

If we wanted a constant object, wouldn't we just declare `const BrickFaceInfo`? I feel like making the members `const` is over-restrictive?
___
*[examples/planar_gripper/planar_gripper_utils.h, line 96 at r1](https://reviewable.io/reviews/rcory/drake/47#-M66Mukb99EsbdatBG6Z:-M6BZ6s75b4CcVN8OuZK:buwvo0w) ([raw file](https://github.com/rcory/drake/blob/bedc7b74c98f3ebc03c35c0a460cc733ffc9080b/examples/planar_gripper/planar_gripper_utils.h#L96)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Could you document why we need to pass `fingers`? Also the input type should be `const std::vector<Finger>&` (const reference).
</blockquote></details>

`force_control_test.cpp` contains a single finger simulation.
___
*[examples/planar_gripper/planar_gripper_utils.h, line 150 at r1](https://reviewable.io/reviews/rcory/drake/47#-M66aGHb20bEas75v9KQ:-M6BefYK7es-kYk1AItM:b-wgkb2l) ([raw file](https://github.com/rcory/drake/blob/bedc7b74c98f3ebc03c35c0a460cc733ffc9080b/examples/planar_gripper/planar_gripper_utils.h#L150)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Maybe instead of returning `int`, and relies on `contact_results.num_point_pair_contacts()` to indicate not found, we could use `std::optional<int>`. If the std::optional<int>()::has_value() is false, then it means the index is not found.
</blockquote></details>

nice observation!
___
*[examples/planar_gripper/planar_gripper_utils.cc, line 150 at r1](https://reviewable.io/reviews/rcory/drake/47#-M6AmNrc5VEj6ey8mKEw:-M6Bes1E2uZ5rSRlBA0G:b-vnuih8) ([raw file](https://github.com/rcory/drake/blob/bedc7b74c98f3ebc03c35c0a460cc733ffc9080b/examples/planar_gripper/planar_gripper_utils.cc#L150)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Just curious, what is the difference between the actual contact point and the witness point when the geometries are in contact? The witness point would be the point with the deepest penetration, so the witness point may not be on the brick surface when the finger penetrates into the brick slightly. Would the contact point computed from `contact_results` be exactly on the brick surface? How does `contact_result` compute the contact point in the first place?
</blockquote></details>

For the point contact model (which we are currently using), the contact point is actually inside the intersection of the two geometries, so it doesn't lie on either surface. Its exact location is a function of the stiffness properties of the two bodies in contact. When the force controller computes a force to be applied, it needs to know exactly where that contact point is (and it generally doesn't match the witness point unless you can make one object **super** stiff, which is bad for numerical reasons I think).

For hydroelastic, the contact point should like on the surface of the rigid object. This should match reality better.
___
*[examples/planar_gripper/planar_gripper_utils.cc, line 234 at r1](https://reviewable.io/reviews/rcory/drake/47#-M6Apbnd4nHOAbxu_F-4:-M6Bh0csAiheTm0fA2KG:b-896fix) ([raw file](https://github.com/rcory/drake/blob/bedc7b74c98f3ebc03c35c0a460cc733ffc9080b/examples/planar_gripper/planar_gripper_utils.cc#L234)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

input type should be `const std::unordered_set<Finger>&`?
</blockquote></details>

Done.
___
*[examples/planar_gripper/planar_gripper_utils.cc, line 237 at r1](https://reviewable.io/reviews/rcory/drake/47#-M6App-Q1qq-ANRDOug5:-M6BhcnlBaQ-w_HTMx5-:b-w8q2t3) ([raw file](https://github.com/rcory/drake/blob/bedc7b74c98f3ebc03c35c0a460cc733ffc9080b/examples/planar_gripper/planar_gripper_utils.cc#L237)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Just curious, why using `constexpr` instead of `const`? I don't think we need `kBoxDimension` to be a compile-time const?
</blockquote></details>

It was a typo. Fixed!
___
*[examples/planar_gripper/planar_gripper_utils.cc, line 238 at r1](https://reviewable.io/reviews/rcory/drake/47#-M6Apuiq-TcTtGKp-Zu_:-M6BhiWgAxedHoDdjwkx:b-896fix) ([raw file](https://github.com/rcory/drake/blob/bedc7b74c98f3ebc03c35c0a460cc733ffc9080b/examples/planar_gripper/planar_gripper_utils.cc#L238)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

const auto&?
</blockquote></details>

Done.
___
*[examples/planar_gripper/test/force_control_test.cc, line 57 at r1](https://reviewable.io/reviews/rcory/drake/47#-M6AqU2HBjkfrJc9WVPj:-M6Bhu8c9ZRAmyLXdkdF:bmrcxbo) ([raw file](https://github.com/rcory/drake/blob/bedc7b74c98f3ebc03c35c0a460cc733ffc9080b/examples/planar_gripper/test/force_control_test.cc#L57)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Curious why we need such a large penetration allowance.
</blockquote></details>

To simulate a very soft fingertip. This will probably change once we get actual robot data, or go to the hydroelastic contact model.

**Review by hongkai-dai — CHANGES_REQUESTED** [review]
:lgtm: 

> Reviewed 3 of 19 files at r1, 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/rcory/drake/47#-:-M6C3rrmD2qoXaZnMiTe:bg7igkv)* status: all files reviewed, 1 unresolved discussion (waiting on @rcory)

___
*[examples/planar_gripper/planar_gripper_utils.h, line 22 at r1](https://reviewable.io/reviews/rcory/drake/47#-M66LuCpCK_YHPcyC6fz:-M6C3N5-BAdRNWRD8V-Q:bu7i25p) ([raw file](https://github.com/rcory/drake/blob/bedc7b74c98f3ebc03c35c0a460cc733ffc9080b/examples/planar_gripper/planar_gripper_utils.h#L22)):*
<details><summary><i>Previously, rcory (Rick Cory) wrote…</i></summary><blockquote>

If we wanted a constant object, wouldn't we just declare `const BrickFaceInfo`? I feel like making the members `const` is over-restrictive?
</blockquote></details>

Make sense.
___
*[examples/planar_gripper/planar_gripper_utils.h, line 96 at r1](https://reviewable.io/reviews/rcory/drake/47#-M66Mukb99EsbdatBG6Z:-M6C3SCL2tH_k9l3Rt0i:btdsfzr) ([raw file](https://github.com/rcory/drake/blob/bedc7b74c98f3ebc03c35c0a460cc733ffc9080b/examples/planar_gripper/planar_gripper_utils.h#L96)):*
<details><summary><i>Previously, rcory (Rick Cory) wrote…</i></summary><blockquote>

`force_control_test.cpp` contains a single finger simulation.
</blockquote></details>

I see.
___
*[examples/planar_gripper/planar_gripper_utils.cc, line 150 at r1](https://reviewable.io/reviews/rcory/drake/47#-M6AmNrc5VEj6ey8mKEw:-M6C3_y3-yb7qZmT2u5L:b-jhyyta) ([raw file](https://github.com/rcory/drake/blob/bedc7b74c98f3ebc03c35c0a460cc733ffc9080b/examples/planar_gripper/planar_gripper_utils.cc#L150)):*
<details><summary><i>Previously, rcory (Rick Cory) wrote…</i></summary><blockquote>

For the point contact model (which we are currently using), the contact point is actually inside the intersection of the two geometries, so it doesn't lie on either surface. Its exact location is a function of the stiffness properties of the two bodies in contact. When the force controller computes a force to be applied, it needs to know exactly where that contact point is (and it generally doesn't match the witness point unless you can make one object **super** stiff, which is bad for numerical reasons I think).

For hydroelastic, the contact point should like on the surface of the rigid object. This should match reality better.
</blockquote></details>

Got it. Thanks!

**Review by hongkai-dai — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/rcory/drake/47)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
