### PR TITLE
Adds hybrid control capability to the PlanarGripper class.

### PR DESCRIPTION
**Pull request by rcory**
* Adds the ability to control the PlanarGripper in hybrid position/torque mode.
* Adds in place final condition tests to simulation demos.
* Includes some other minor general cleanup and fixes.

---
This change is [Reviewable](https://reviewable.io/reviews/rcory/drake/42)

### CODE REVIEW

**Review by rcory — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/rcory/drake/42#-:-M57_RO_6iSHEcC0rN8E:b-v2y4sj)* status: 0 of 14 files reviewed, all discussions resolved

**Review by rcory — COMMENTED** [review]
The diagram above shows the new systems and interconnections added to support hybrid control for the planar-gripper, and is done in the `PlanarGripper::Finalize()` method. Just for reference.

@hongkai-dai for review please. Sorry for the long PR. Also note, CI is offline at the moment.

> *[Reviewable](https://reviewable.io/reviews/rcory/drake/42#-:-M57a0sADY2YJ2AOZr3k:bh21w2c)* status: 0 of 14 files reviewed, all discussions resolved

**Review by hongkai-dai — COMMENTED** [review]
+@hongkai-dai for review.

> *[Reviewable](https://reviewable.io/reviews/rcory/drake/42#-:-M57gT-D11Re15vl7DJE:blyxpiv)* status: 0 of 14 files reviewed, all discussions resolved (waiting on @hongkai-dai)

**Review by hongkai-dai — CHANGES_REQUESTED** [review]
Checkpoint

> Reviewed 3 of 14 files at r1.
> *[Reviewable](https://reviewable.io/reviews/rcory/drake/42#-:-M57tt-k-8XyUsCeX5vj:b13s2ul)* status: 3 of 14 files reviewed, 2 unresolved discussions (waiting on @hongkai-dai and @rcory)

___
*[examples/planar_gripper/planar_gripper.cc, line 196 at r1](https://reviewable.io/reviews/rcory/drake/42#-M57sp3J7K7TTT4eJiZZ:-M57sp3J7K7TTT4eJiZ_:b-2bwvy3) ([raw file](https://github.com/rcory/drake/blob/0407ad82c754b1d3ff3da54c83d718aff86c2304/examples/planar_gripper/planar_gripper.cc#L196)):*
> ```cpp
>   }
> 
>   Finger get_finger() {
> ```

const function?
___
*[examples/planar_gripper/planar_gripper_common.h, line 170 at r1](https://reviewable.io/reviews/rcory/drake/42#-M57iXDr1JOWARxaFyiE:-M57iXE54-Tve8vVf_bm:b-cch1kn) ([raw file](https://github.com/rcory/drake/blob/0407ad82c754b1d3ff3da54c83d718aff86c2304/examples/planar_gripper/planar_gripper_common.h#L170)):*
> ```objc
> /// ordering defined here ensures joint ordering is by finger number, and each
> /// finger is ordered according to GetPreferredFingerJointOrdering().
> std::vector<std::string> GetPreferredGripperJointOrdering();
> ```

Can we add a unit test for this function?

**Review by rcory — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/rcory/drake/42)* status: 2 of 15 files reviewed, 2 unresolved discussions (waiting on @hongkai-dai)

___
*[examples/planar_gripper/planar_gripper.cc, line 196 at r1](https://reviewable.io/reviews/rcory/drake/42#-M57sp3J7K7TTT4eJiZZ:-M58QLXs39r4KokC3RmT:b-896fix) ([raw file](https://github.com/rcory/drake/blob/0407ad82c754b1d3ff3da54c83d718aff86c2304/examples/planar_gripper/planar_gripper.cc#L196)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

const function?
</blockquote></details>

Done.
___
*[examples/planar_gripper/planar_gripper_common.h, line 170 at r1](https://reviewable.io/reviews/rcory/drake/42#-M57iXDr1JOWARxaFyiE:-M58xLOMA9J81FCCztP5:b-896fix) ([raw file](https://github.com/rcory/drake/blob/0407ad82c754b1d3ff3da54c83d718aff86c2304/examples/planar_gripper/planar_gripper_common.h#L170)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Can we add a unit test for this function?
</blockquote></details>

Done.

**Review by hongkai-dai — CHANGES_REQUESTED** [review]
:lgtm: 

> Reviewed 10 of 14 files at r1, 2 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/rcory/drake/42#-:-M5NfDXg8JZXpdc_zWYC:bg7igkv)* status: 13 of 15 files reviewed, 4 unresolved discussions (waiting on @hongkai-dai and @rcory)

___
*[examples/planar_gripper/planar_gripper.cc, line 241 at r2](https://reviewable.io/reviews/rcory/drake/42#-M5NbjE01Ruh2Hxsz7vt:-M5NbjE01Ruh2Hxsz7vu:b-vohv46) ([raw file](https://github.com/rcory/drake/blob/3eacb7d4b6d4a03e96b8ead00682cc74e62e6171/examples/planar_gripper/planar_gripper.cc#L241)):*
> ```cpp
>  * as needed by the desired state input port of the InverseDynamicsController).
>  */
> class FingersStateToGripperState : public systems::LeafSystem<double> {
> ```

Should this class be a `final` derived class?
___
*[examples/planar_gripper/planar_gripper.cc, line 309 at r2](https://reviewable.io/reviews/rcory/drake/42#-M5Nbci93Yyw48cDLO2o:-M5Nbci93Yyw48cDLO2p:b-vohv46) ([raw file](https://github.com/rcory/drake/blob/3eacb7d4b6d4a03e96b8ead00682cc74e62e6171/examples/planar_gripper/planar_gripper.cc#L309)):*
> ```cpp
>  * according to GetPreferredGripperJointOrdering().
>  */
> class GripperActuationToPreferredOrdering : public systems::LeafSystem<double> {
> ```

Should this class be a `final` derived class?
___
*[examples/planar_gripper/planar_gripper.cc, line 358 at r2](https://reviewable.io/reviews/rcory/drake/42#-M5NbnbVDnbRIPWpPqU7:-M5NbnbVDnbRIPWpPqU8:b-vohv46) ([raw file](https://github.com/rcory/drake/blob/3eacb7d4b6d4a03e96b8ead00682cc74e62e6171/examples/planar_gripper/planar_gripper.cc#L358)):*
> ```cpp
>  * is of size kNumGripperJoints.
>  */
> class FingersToGripperActuation : public systems::LeafSystem<double> {
> ```

Should this class be a `final` derived class?
___
*[examples/planar_gripper/planar_gripper.cc, line 572 at r2](https://reviewable.io/reviews/rcory/drake/42#-M5Nc3az2yV_rz4IVS0S:-M5Nc3az2yV_rz4IVS0T:b-3f62zk) ([raw file](https://github.com/rcory/drake/blob/3eacb7d4b6d4a03e96b8ead00682cc74e62e6171/examples/planar_gripper/planar_gripper.cc#L572)):*
> ```cpp
>   // chosen arbitrarily.
>   Vector<double, kNumGripperJoints> Kp, Kd, Ki;
>   Kp.setConstant(1500);
> ```

Do you think it is possible to change these gains in the future? If so, shall we add `Kp, Kd, Ki` as input argument of this function?

**Review by rcory — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/rcory/drake/42)* status: 10 of 16 files reviewed, 4 unresolved discussions (waiting on @hongkai-dai)

___
*[examples/planar_gripper/planar_gripper.cc, line 241 at r2](https://reviewable.io/reviews/rcory/drake/42#-M5NbjE01Ruh2Hxsz7vt:-M5NlzN72HAxRx8xYeI1:b-896fix) ([raw file](https://github.com/rcory/drake/blob/3eacb7d4b6d4a03e96b8ead00682cc74e62e6171/examples/planar_gripper/planar_gripper.cc#L241)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Should this class be a `final` derived class?
</blockquote></details>

Done.
___
*[examples/planar_gripper/planar_gripper.cc, line 309 at r2](https://reviewable.io/reviews/rcory/drake/42#-M5Nbci93Yyw48cDLO2o:-M5Nm1jlA3Dnn1T66yMX:b-896fix) ([raw file](https://github.com/rcory/drake/blob/3eacb7d4b6d4a03e96b8ead00682cc74e62e6171/examples/planar_gripper/planar_gripper.cc#L309)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Should this class be a `final` derived class?
</blockquote></details>

Done.
___
*[examples/planar_gripper/planar_gripper.cc, line 358 at r2](https://reviewable.io/reviews/rcory/drake/42#-M5NbnbVDnbRIPWpPqU7:-M5Nm50M-PscpQiOHVxh:b-896fix) ([raw file](https://github.com/rcory/drake/blob/3eacb7d4b6d4a03e96b8ead00682cc74e62e6171/examples/planar_gripper/planar_gripper.cc#L358)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Should this class be a `final` derived class?
</blockquote></details>

Done.
___
*[examples/planar_gripper/planar_gripper.cc, line 572 at r2](https://reviewable.io/reviews/rcory/drake/42#-M5Nc3az2yV_rz4IVS0S:-M5OBJ4u55Zckud-uJF1:b-896fix) ([raw file](https://github.com/rcory/drake/blob/3eacb7d4b6d4a03e96b8ead00682cc74e62e6171/examples/planar_gripper/planar_gripper.cc#L572)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Do you think it is possible to change these gains in the future? If so, shall we add `Kp, Kd, Ki` as input argument of this function?
</blockquote></details>

Done.

**Review by hongkai-dai — APPROVED** [review]
> Reviewed 1 of 4 files at r2, 5 of 5 files at r3.
> *[Reviewable](https://reviewable.io/reviews/rcory/drake/42)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
