### PR TITLE
* Adds a position to force control simulation.

### PR DESCRIPTION
**Pull request by rcory**
* Also adds a utility to print keyframes to standard out.
* Adds utility to create a state selector matrix from a preferred
ordering.

---
This change is [Reviewable](https://reviewable.io/reviews/rcory/drake/45)

### CODE REVIEW

**Review by rcory — COMMENTED** [review]
+@hongkai-dai for review please.

> *[Reviewable](https://reviewable.io/reviews/rcory/drake/45#-:-M5YcHhY6c-S4MjoHKML:b-jjzuh1)* status: 0 of 8 files reviewed, all discussions resolved (waiting on @hongkai-dai)

**Review by hongkai-dai — CHANGES_REQUESTED** [review]
:lgtm:  just minor comments.

> Reviewed 8 of 8 files at r1.
> *[Reviewable](https://reviewable.io/reviews/rcory/drake/45#-:-M5_MZLE8kzlr4HpUjDy:bt6jap8)* status: all files reviewed, 4 unresolved discussions (waiting on @rcory)

___
*[examples/planar_gripper/planar_gripper_common.h, line 174 at r1](https://reviewable.io/reviews/rcory/drake/45#-M5_LOBS3_E9gbW_xRLm:-M5_LOBS3_E9gbW_xRLn:bigjl7y) ([raw file](https://github.com/rcory/drake/blob/d5e1303ddedd1114be4d18ab54c681ad7770506d/examples/planar_gripper/planar_gripper_common.h#L174)):*
> ```objc
> /// Returns the state plant's state selector matrix corresponding to the
> /// provided joint names in PlanarGripper.
> MatrixX<double> MakeStateSelectorMatrix(
> ```

BTW, maybe it is better to add a unit test for this function?
___
*[examples/planar_gripper/planar_gripper_common.cc, line 428 at r1](https://reviewable.io/reviews/rcory/drake/45#-M5_KzsR08f7AwVnPJuM:-M5_KzsR08f7AwVnPJuN:b-jrbhy7) ([raw file](https://github.com/rcory/drake/blob/d5e1303ddedd1114be4d18ab54c681ad7770506d/examples/planar_gripper/planar_gripper_common.cc#L428)):*
> ```cpp
>     const MultibodyPlant<double>& plant,
>     const std::vector<std::string>& joint_names) {
>   std::vector<multibody::JointIndex> joint_indices;
> ```

BTW, you could allocate the size of this `joint_indices` first, its size is `joint_names.size()`, so that we can avoid potential memory re-allocation in the for loop below.
___
*[examples/planar_gripper/planar_gripper_utils.h, line 104 at r1](https://reviewable.io/reviews/rcory/drake/45#-M5_K1npCJt02EP0rbKy:-M5_K1npCJt02EP0rbKz:bo2nwbf) ([raw file](https://github.com/rcory/drake/blob/d5e1303ddedd1114be4d18ab54c681ad7770506d/examples/planar_gripper/planar_gripper_utils.h#L104)):*
> ```objc
> 
>   PrintKeyframes(const MultibodyPlant<double>& plant,
>                  std::vector<std::string> joint_names, double period,
> ```

const std::vector<std::string>&?
___
*[examples/planar_gripper/planar_gripper_utils.h, line 105 at r1](https://reviewable.io/reviews/rcory/drake/45#-M5_JzVL4gLU-y_bqIP9:-M5_JzVM5eWArgWDmbjl:be00gex) ([raw file](https://github.com/rcory/drake/blob/d5e1303ddedd1114be4d18ab54c681ad7770506d/examples/planar_gripper/planar_gripper_utils.h#L105)):*
> ```objc
>   PrintKeyframes(const MultibodyPlant<double>& plant,
>                  std::vector<std::string> joint_names, double period,
>                  bool print_time);
> ```

Could you explain what print_time is? I am surprised that a variable with name "time" is of type `bool`. 
___
*[examples/planar_gripper/planar_gripper_utils.cc, line 3 at r1](https://reviewable.io/reviews/rcory/drake/45#-M5_KDz82SKhwU8oBIvl:-M5_KDz82SKhwU8oBIvm:b-6iu48l) ([raw file](https://github.com/rcory/drake/blob/d5e1303ddedd1114be4d18ab54c681ad7770506d/examples/planar_gripper/planar_gripper_utils.cc#L3)):*
> ```cpp
> #include "drake/examples/planar_gripper/planar_gripper_utils.h"
> 
> #include <string>
> ```

No need to include them here? As they are included in the header file already.
___
*[examples/planar_gripper/planar_gripper_utils.cc, line 140 at r1](https://reviewable.io/reviews/rcory/drake/45#-M5_KRJB-EU7qEyaq3jO:-M5_KRJB-EU7qEyaq3jP:bkxr1x8) ([raw file](https://github.com/rcory/drake/blob/d5e1303ddedd1114be4d18ab54c681ad7770506d/examples/planar_gripper/planar_gripper_utils.cc#L140)):*
> ```cpp
>   Sx_ = MakeStateSelectorMatrix(plant, joint_names);
>   std::cout << "keyframe_dt=" << period << std::endl;
>   for (auto iter : joint_names) {
> ```

const auto& iter?

**Review by rcory — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/rcory/drake/45)* status: 5 of 9 files reviewed, 4 unresolved discussions (waiting on @hongkai-dai)

___
*[examples/planar_gripper/planar_gripper_utils.h, line 104 at r1](https://reviewable.io/reviews/rcory/drake/45#-M5_K1npCJt02EP0rbKy:-M5ce7S-34af4T7Tfkl4:b-896fix) ([raw file](https://github.com/rcory/drake/blob/d5e1303ddedd1114be4d18ab54c681ad7770506d/examples/planar_gripper/planar_gripper_utils.h#L104)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

const std::vector<std::string>&?
</blockquote></details>

Done.
___
*[examples/planar_gripper/planar_gripper_utils.h, line 105 at r1](https://reviewable.io/reviews/rcory/drake/45#-M5_JzVL4gLU-y_bqIP9:-M5cf5WECWEToRLoXV6l:b-896fix) ([raw file](https://github.com/rcory/drake/blob/d5e1303ddedd1114be4d18ab54c681ad7770506d/examples/planar_gripper/planar_gripper_utils.h#L105)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Could you explain what print_time is? I am surprised that a variable with name "time" is of type `bool`. 
</blockquote></details>

Done.
___
*[examples/planar_gripper/planar_gripper_utils.cc, line 3 at r1](https://reviewable.io/reviews/rcory/drake/45#-M5_KDz82SKhwU8oBIvl:-M5cfAgj9klbqM1k-fHw:b-896fix) ([raw file](https://github.com/rcory/drake/blob/d5e1303ddedd1114be4d18ab54c681ad7770506d/examples/planar_gripper/planar_gripper_utils.cc#L3)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

No need to include them here? As they are included in the header file already.
</blockquote></details>

Done.
___
*[examples/planar_gripper/planar_gripper_utils.cc, line 140 at r1](https://reviewable.io/reviews/rcory/drake/45#-M5_KRJB-EU7qEyaq3jO:-M5cfLktEUe5XQ2dhdMt:b-896fix) ([raw file](https://github.com/rcory/drake/blob/d5e1303ddedd1114be4d18ab54c681ad7770506d/examples/planar_gripper/planar_gripper_utils.cc#L140)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

const auto& iter?
</blockquote></details>

Done.

**Review by hongkai-dai — APPROVED** [review]
> Reviewed 4 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/rcory/drake/45)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
