### PR TITLE
Fixes various vector sizes (previously hard coded)

### PR DESCRIPTION
**Pull request by rcory**
- Fixes various vector sizes (previously hard coded) to support both pin brick and planar brick spatial force planning.
- Also some documentation cleanup.

---
This change is [Reviewable](https://reviewable.io/reviews/rcory/drake/26)

### CODE REVIEW

**Review by rcory — COMMENTED** [review]
+@hongkai-dai for review please.

> *[Reviewable](https://reviewable.io/reviews/rcory/drake/26#-:-M2sptl29Y9S_AgXHjz5:b-jjzuh1)* status: 0 of 6 files reviewed, all discussions resolved (waiting on @hongkai-dai)

**Review by hongkai-dai — CHANGES_REQUESTED** [review]
> Reviewed 6 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/rcory/drake/26)* status: all files reviewed, 1 unresolved discussion (waiting on @rcory)

___
*[examples/planar_gripper/contact_force_qp.h, line 34 at r1](https://reviewable.io/reviews/rcory/drake/26#-M2tsCFZ1plijA-gDNjk:-M2tsCFZ1plijA-gDNjl:b-28d51k) ([raw file](https://github.com/rcory/drake/blob/8c11e9afa92507d38b2b8ce734d987e838c27dd5/examples/planar_gripper/contact_force_qp.h#L34)):*
> ```objc
>  *
>  *     min   w₁ * |p̈_WB - p̈ᵈᵉˢ_WB|² + w₂  * |θ̈ - θ̈ᵈᵉˢ|² + w₃ * |f_Cb_B|²
>  *     s.t   m * p̈_WB = m * g_W + R_WB * ∑ f_Cb_B - (D_t * ṗ_WB)
> ```

I am not sure if we should model the sliding friction force/torque with the damping term. I think it is more like a constant magnitude force plus a term proportional to the velocity, namely 
f_sliding = f_magnitude * pdot_WB / |pdot_WB| + D_t * pdot_WB
where f_magnitude is a constant term.

**Review by rcory — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/rcory/drake/26)* status: 5 of 6 files reviewed, 1 unresolved discussion (waiting on @hongkai-dai)

___
*[examples/planar_gripper/contact_force_qp.h, line 34 at r1](https://reviewable.io/reviews/rcory/drake/26#-M2tsCFZ1plijA-gDNjk:-M2tzxY_-IlSJOJ3EfPp:bp9p3en) ([raw file](https://github.com/rcory/drake/blob/8c11e9afa92507d38b2b8ce734d987e838c27dd5/examples/planar_gripper/contact_force_qp.h#L34)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

I am not sure if we should model the sliding friction force/torque with the damping term. I think it is more like a constant magnitude force plus a term proportional to the velocity, namely 
f_sliding = f_magnitude * pdot_WB / |pdot_WB| + D_t * pdot_WB
where f_magnitude is a constant term.
</blockquote></details>

Fyi, this isn't supposed to capture stiction or coulomb friction terms (I've added a todo there to clarify), and it is what issue #15 captures. Viscous damping is what you get when you make the `<damping>` tag in `sdf` non-zero, which is why I included it here.

**Review by hongkai-dai — COMMENTED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/rcory/drake/26#-:-M2u4qXu8BDcypwX7tar:bg7igkv)* status: 5 of 6 files reviewed, all discussions resolved (waiting on @hongkai-dai)

**Review by hongkai-dai — APPROVED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/rcory/drake/26)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
