### PR TITLE
Fixes playback frame visualization.

### PR DESCRIPTION
**Pull request by rcory**
* Fixes playback frame visualization.
* Replaces postures.txt with an updated planar-brick contact-explicit plan.
* Removes outdated postures_new.txt.
* Adds two pinned brick, contact-explicit, motion plan files (pinned_brick_postures_01/02.txt).

---
This change is [Reviewable](https://reviewable.io/reviews/rcory/drake/33)

### CODE REVIEW

**Review by rcory — COMMENTED** [review]
+@hongkai-dai for review, please.

> *[Reviewable](https://reviewable.io/reviews/rcory/drake/33#-:-M4QtipPAmkMXIFKRe2f:b-caag4n)* status: 0 of 8 files reviewed, all discussions resolved (waiting on @hongkai-dai)

**Review by hongkai-dai — CHANGES_REQUESTED** [review]
:lgtm: 

> Reviewed 9 of 9 files at r1.
> *[Reviewable](https://reviewable.io/reviews/rcory/drake/33#-:-M4SCXTcEB9IG-KSE89y:bg7igkv)* status: all files reviewed, 1 unresolved discussion (waiting on @rcory)

___
*[examples/planar_gripper/planar_gripper_common.cc, line 432 at r1](https://reviewable.io/reviews/rcory/drake/33#-M4SALxe7BbrZfyxkb0W:-M4SALxf1l730WYIpc4W:b-e1swj6) ([raw file](https://github.com/rcory/drake/blob/89e5eda7816c6e12345b96b2840c0434548b393c/examples/planar_gripper/planar_gripper_common.cc#L432)):*
> ```cpp
>     const drake::systems::Context<double>& context) const {
>   if (frames_input_) {
>     auto frames_vec =
> ```

const auto?
___
*[examples/planar_gripper/run_playback_gripper_keyframes.cc, line 58 at r1](https://reviewable.io/reviews/rcory/drake/33#-M4SAkQz8hFbLemjnZVj:-M4SAkQz8hFbLemjnZVk:bcli1y1) ([raw file](https://github.com/rcory/drake/blob/89e5eda7816c6e12345b96b2840c0434548b393c/examples/planar_gripper/run_playback_gripper_keyframes.cc#L58)):*
> ```cpp
>                   plant.GetBodyByName(body_names[i]).index()),
>               geometry_roles[i], geometry_names[i]);
>       geometry_frame_ids_.push_back(
> ```

BTW, we could resize geometry_frame_ids_ as
```C++
geometry_frame_ids_.resize(body_names.size());
```
before this for loop, that will avoid some dynamic memory allocation for each iteration of the for loop.

**Review by rcory — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/rcory/drake/33)* status: 7 of 9 files reviewed, 1 unresolved discussion (waiting on @hongkai-dai)

___
*[examples/planar_gripper/planar_gripper_common.cc, line 432 at r1](https://reviewable.io/reviews/rcory/drake/33#-M4SALxe7BbrZfyxkb0W:-M4UN1yR8y8vfpIN0Obo:b-896fix) ([raw file](https://github.com/rcory/drake/blob/89e5eda7816c6e12345b96b2840c0434548b393c/examples/planar_gripper/planar_gripper_common.cc#L432)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

const auto?
</blockquote></details>

Done.
___
*[examples/planar_gripper/run_playback_gripper_keyframes.cc, line 58 at r1](https://reviewable.io/reviews/rcory/drake/33#-M4SAkQz8hFbLemjnZVj:-M4UOU8d8mhnfR6RS4FP:b-896fix) ([raw file](https://github.com/rcory/drake/blob/89e5eda7816c6e12345b96b2840c0434548b393c/examples/planar_gripper/run_playback_gripper_keyframes.cc#L58)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

BTW, we could resize geometry_frame_ids_ as
```C++
geometry_frame_ids_.resize(body_names.size());
```
before this for loop, that will avoid some dynamic memory allocation for each iteration of the for loop.
</blockquote></details>

Done.

**Review by hongkai-dai — APPROVED** [review]
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/rcory/drake/33)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
