### PR TITLE
Add UDP message types.

### PR DESCRIPTION
**Pull request by hongkai-dai**
Add UDP message structs for the message that would go from sim to QP controller and vice versa.

---
This change is [Reviewable](https://reviewable.io/reviews/rcory/drake/2)

### CODE REVIEW

**Review by rcory — COMMENTED** [review]
> Reviewed 4 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/rcory/drake/2)* status: all files reviewed, 3 unresolved discussions (waiting on @hongkai-dai)

___
*[examples/planar_gripper/BUILD.bazel, line 87 at r1](https://reviewable.io/reviews/rcory/drake/2#-M0x6WsX3wX0eTS16aGa:-M0x6WsYCJboayZaAtqi:b-iki60m) ([raw file](https://github.com/rcory/drake/blob/9e91df25dedd71b73ab1526093f889b4f27934e3/examples/planar_gripper/BUILD.bazel#L87)):*
> ```Starlark
> #        "//systems/framework:leaf_system",
> #    ],
> #)
> ```

Why are we commenting out the LCM version? I think having the LCM version work as a baseline is valuable.
___
*[examples/planar_gripper/BUILD.bazel, line 378 at r1](https://reviewable.io/reviews/rcory/drake/2#-M0x6hPl3L-PrYc4Qnte:-M0x6hPl3L-PrYc4Qntf:bf8zvde) ([raw file](https://github.com/rcory/drake/blob/9e91df25dedd71b73ab1526093f889b4f27934e3/examples/planar_gripper/BUILD.bazel#L378)):*
> ```Starlark
> )
> 
> #drake_cc_googletest(
> ```

Same comment as above....I don't think we should comment out the LCM versions.
___
*[examples/planar_gripper/planar_gripper_udp.cc, line 51 at r1](https://reviewable.io/reviews/rcory/drake/2#-M0x9cEODMPuf6ajurah:-M0x9cEODMPuf6ajurai:b-57nw2x) ([raw file](https://github.com/rcory/drake/blob/9e91df25dedd71b73ab1526093f889b4f27934e3/examples/planar_gripper/planar_gripper_udp.cc#L51)):*
> ```cpp
> }
> 
> int FingerFaceAssignments::DoMessageSize() const {
> ```

nit I would probably rename the `DoMessageSize()` methods (here and below) to`GetMessageSize()`.  (sounds odd otherwise).

**Review by hongkai-dai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/rcory/drake/2)* status: all files reviewed, 2 unresolved discussions (waiting on @rcory)

___
*[examples/planar_gripper/BUILD.bazel, line 87 at r1](https://reviewable.io/reviews/rcory/drake/2#-M0x6WsX3wX0eTS16aGa:-M0xHI653RFyccuPwmOx:b6r9s7) ([raw file](https://github.com/rcory/drake/blob/9e91df25dedd71b73ab1526093f889b4f27934e3/examples/planar_gripper/BUILD.bazel#L87)):*
<details><summary><i>Previously, rcory (Rick Cory) wrote…</i></summary><blockquote>

Why are we commenting out the LCM version? I think having the LCM version work as a baseline is valuable.
</blockquote></details>

Per f2f discussion, there is a build error.
___
*[examples/planar_gripper/BUILD.bazel, line 378 at r1](https://reviewable.io/reviews/rcory/drake/2#-M0x6hPl3L-PrYc4Qnte:-M0xHKn_2H75u41HYbyu:b-89a4l7) ([raw file](https://github.com/rcory/drake/blob/9e91df25dedd71b73ab1526093f889b4f27934e3/examples/planar_gripper/BUILD.bazel#L378)):*
<details><summary><i>Previously, rcory (Rick Cory) wrote…</i></summary><blockquote>

Same comment as above....I don't think we should comment out the LCM versions.
</blockquote></details>

Ditto
___
*[examples/planar_gripper/planar_gripper_udp.cc, line 51 at r1](https://reviewable.io/reviews/rcory/drake/2#-M0x9cEODMPuf6ajurah:-M0xHLxF9j4F1EDxlQkL:b-xhi8c) ([raw file](https://github.com/rcory/drake/blob/9e91df25dedd71b73ab1526093f889b4f27934e3/examples/planar_gripper/planar_gripper_udp.cc#L51)):*
<details><summary><i>Previously, rcory (Rick Cory) wrote…</i></summary><blockquote>

nit I would probably rename the `DoMessageSize()` methods (here and below) to`GetMessageSize()`.  (sounds odd otherwise).
</blockquote></details>

Done. I renamed this to GetMessageSize and DoGetMessageSize. I don't have a `message_size_` data field, so our naming convention requires to use a verb in the function name, to indicate that there is some cost to call this function.

**Review by rcory — APPROVED** [review]
> Reviewed 3 of 3 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/rcory/drake/2)* status: all files reviewed, 2 unresolved discussions (waiting on @rcory)

**Review by rcory — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/rcory/drake/2)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by rcory — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/rcory/drake/2#-:-M0xbA9V52vkttktUs6j:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
